### ISSUE TITLE
Support `convert(::Type{ReadOnlyArray{T}}, Array{T})`?

### ISSUE THREAD

**Issue by wmanning-cra** [bkamins/ReadOnlyArrays.jl#3]
I think it would be very useful to add an implicit conversion from an array to a read-only array.

**Comment by bkamins** [comment]
It should probably be for `AbstractArray`. I think it is OK to add it. If you would find it useful please go ahead and make a PR.

**Comment by wmanning-cra** [comment]
https://github.com/bkamins/ReadOnlyArrays.jl/pull/5
