### ISSUE TITLE
Define `ReadOnlyVector` and `ReadOnlyMatrix`

### ISSUE THREAD

**Issue by wmanning-cra** [bkamins/ReadOnlyArrays.jl#4]
Self-explanatory

**Comment by bkamins** [comment]
If you would find it useful I am OK to add it. Please go ahead and make a PR. The only thing to discuss if you want eg. `ReadOnlyVector` to enforce `Vector` or `AbstractVector`? I think the latter is better.

**Comment by wmanning-cra** [comment]
Just made a PR for them. They are merely aliases for `ReadOnlyArray`, so they don't refer to `Vector` or `AbstractVector` at all.

https://github.com/bkamins/ReadOnlyArrays.jl/pull/5
